apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: '2023-11-22T16:30:55Z'
  generation: 1
  labels:
    app: frontend
  name: llm-demo
  namespace: prometheus
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - tgis-llm-demo
  selector:
    matchLabels:
      app: gradio-hftgi-rag-redis-flan
